### ISSUE TITLE
In combat DC results in death

### ISSUE THREAD

**Issue by Whudunnit** [Damieninabox/Lotus-WoW-Bugtracker#15]
**Describe the bug**
A lot of private servers have and had this issue in the past. If you are in combat with an NPC and then disconnect or force close the game with ALT + F4, then you immediately die when you log back in, NO MATTER your hp.

**To Reproduce**
Get in combat with any mob > ALT + F4 > Log back in > you are dead

**Additional context**
Tested this in Ghostlands multiple times with max hp. Always dead in 5 seconds before logging back. This will cause major problems whenever the server crashes in the future.

**Comment by Missix12** [comment]
I tried this, once when server was restarting and second time just alt + f4 in combat.
Both times when I came back to my corpse I was unable to resurrect no matter how many times I press that button its just impossible to ress. I'm not sure if that's only me (because you haven't said anything about bugged ress) but it happened every time. I don't have any addons installed.

**Comment by Whudunnit** [comment]
I have a whole host of addons and I never had a problem with ressing.

**Comment by Damieninabox** [comment]
Same behavior as on retail since day 1

**Comment by Greymane** [comment]
Retail behavior, closing this one
