### ISSUE TITLE
[Raid] Mogu'shan Vaults

### ISSUE THREAD

**Issue by TellyO3** [Damieninabox/Lotus-WoW-Bugtracker#380]
**Stone Guard**

- Timer for activating the next petrification seems to be off, it took about 10-20 seconds for a new guardian to start casting petrification at one point.

**Garajal**

- Seems to be a combat bug somewhere here, unclear where we picked it up.
- The totems on the railings are targetable and killable before the boss is even pulled

**Spirit Kings**

- Mind Control is fucked, it doesn't seem to go away and when it does it often doesn't register the player as being friendly again, leaving them unable to be healed. 

**Elegon**

- Many cosmetic issues
- Elegon is too low, he clips through the floor.
- In phase two opposing Emphyricals (the pylons) should be linked, their wall should only go down once both are destroyed.
- They are also supposed to have an effect between them, a laser cosmetic. 

We didn't do the last boss, will add some clips and additional resources later.

**Comment by BanHammer69** [comment]
Adding my comments + SK has entire video footage of these notes in case you want confirmation of the points here:

**Stone Guard**
- Energy Gain radius is too large hence impacting taunt swapping. (I'm the tank with 2 dogs but when swapping even the other tank's single dog was gaining energy when we were on opposite sides of the red central curtain) Energy gain should not occur once dogs are 12 yards apart
- Petrification is not applying correctly. During our fight even though we did the correct swap to ensure Overload was on petrifying dog entire raid took massive overload damage without dampening from petrification (we only survived it due to high gear levels)
- Even though there is no fix, mentioning it here since it may have to do with trigger scripts. DBM/Big Wigs are not working as intended E.g. For this fight, SK's DBM did not display the Boss Information Panel (with all dog's energy levels and which one had Petrification etc.) My Big Wigs is unable to post when Amber Pools, Cobalt Mines, Jade Chains etc. are in effect so have to rely on visual cues entirely

**Feng the Accursed**
- The tank crystal at start is bugged. I was taking Nullification Barrier and on blizzlike I should need just one click but on Lotus I need 4-5 clicks for crystal to register as my Boss button but by then Boss has already been aggro'd from my first click. Crystal activation on my boss button and boss aggro should happen simultaneously
- Nullification Barrier is bugged. Being a channeled spell I have to remain still to ensure full invulnerability frames. However, even on being still, the barrier is ending well before it's full duration (barrier duration should be greater than Epicenter duration)
- Cannot comment on Shroud of Reversal since other tank didn't pick it up 

**Garajal** 

- Combat bug impacted ALL timers and boss events. The only indicator that worked was when the other tank (who started the encounter) was banished. FeelsOkayMan had to reset our combat bug after we killed boss. 

**Spirit Kings**

- Meng the Demented encounter is bugged. His 'Crazed' and 'Cowardice' personality switches are not announced and Maddening Shout is not working as intended. 
Examples: 
1) Isaac's mage would not leave Mind Control when I used abilities on him. I had to melee him for damage to register
2) Blizzlike needs only 40k dmg to break MC. However Tronco's chain lighting damaged me for 275k since it kept registering me as an enemy
3) SK's heals were killing people since they registered as hostiles

- Zian of the endless Shadow cast his abilities and shadow spawns way too fast for any alerts to be announced and wiped everyone else in the entire raid. I had to solo him for the boss kill. The alert/announcement for his 'Shield of Darkness' has to work perfectly else dps won't know when to stop hitting him to avoid raid wipes  

**Elegon**
- **Please rework the entire encounter.** I've shared a video link with SK on a tank PoV of this encounter so that you can observe all mechanics/interactions as intended. At this point of time during the raid, we weren't attempting the boss correctly so unable to provide in-depth comments. 
- Aside from cosmetic bugs above, the 'Celestial Protector' is completely bugged. It should spawn at the edge of outer ring and then run to boss giving time for other tank to taunt it and keep away from the boss close to the edge. On Lotus, the protector spawns under the boss itself and is immune to taunts (bug) and the only way to draw protector is to actually melee him. Not working as intended

**Comment by Greymane** [comment]
@TellyO3 @BanHammer69 Can one of you provide a video for the stone guard issues at least? its the only encounter i have issues reproducing the bugs because due to the nature of the fight, its hard to do it alone with multiple clients open.

Some comments on the issues listed tho that i kinda managed to find where the problem lies.

> Timer for activating the next petrification seems to be off, it took about 10-20 seconds for a new guardian to start casting petrification at one point.

~~Initial petrification (boss initial pull) is indeed a bit off, 8s from engage timer + 6.5s-7s after those 8s (so total time around 15s).
Petrification is scheduled to happen 6.5-7s after the guardian overloads.~~

> Energy Gain radius is too large hence impacting taunt swapping. (I'm the tank with 2 dogs but when swapping even the other tank's single dog was gaining energy when we were on opposite sides of the red central curtain) Energy gain should not occur once dogs are 12 yards apart

This was caused by the event timer that was being used to check if there are or not guardians nearby, it was set to check every 2s, i lowered it to 200ms and i assume it should be good now.

> Petrification is not applying correctly. During our fight even though we did the correct swap to ensure Overload was on petrifying dog entire raid took massive overload damage without dampening from petrification (we only survived it due to high gear levels)

Will TRY to check this, my eye didnt catch anything suspicious on the code so far.

> Even though there is no fix, mentioning it here since it may have to do with trigger scripts. DBM/Big Wigs are not working as intended E.g. For this fight, SK's DBM did not display the Boss Information Panel (with all dog's energy levels and which one had Petrification etc.) My Big Wigs is unable to post when Amber Pools, Cobalt Mines, Jade Chains etc. are in effect so have to rely on visual cues entirely

Could you provide a link to this addon of yours? i could try and fix it.

Thanks in advance.

**Comment by Greymane** [comment]
Ok, overload damage dampening trough petrification [seems to be working fine](https://puu.sh/IZNR6/e38ce98d3f.jpg)

**Comment by Greymane** [comment]
> Nullification Barrier is bugged. Being a channeled spell I have to remain still to ensure full invulnerability frames. However, even on being still, the barrier is ending well before it's full duration (barrier duration should be greater than Epicenter duration)

Invalid, shield is supposed to have 6s duration and not last during the full duration of epicenter, confirmed on https://youtu.be/_TvPI1-_c8E?t=61, channel begins at around 1:02.5 seconds, and ends at 1:08.5

**Comment by Greymane** [comment]
> Meng the Demented encounter is bugged. His 'Crazed' and 'Cowardice' personality switches are not announced and Maddening Shout is not working as intended.

Announces [seems to be working](https://puu.sh/IBYXF/66cb2102ae.jpg), if you have an addon, check fatboss guide and so far the boss itself has no MonsterEmote for these 2 spells (monsteremote being the big yellow test they show in the screen, not addon based). Same for the charged shadows and undying shadows announcements. 

Maddening Shout should be now working as intended.

**Comment by TellyO3** [comment]
@Greymane Don't use Fatboss those guides are made on PTR realms and do not reflect the encounters in their final form, @BanHammer69 can confirm this.

**Comment by Greymane** [comment]
Oh, i see, well gotta a need a new source of information then
